(() => {
  if (window.__cryptoCopilotCentralV402) return;
  window.__cryptoCopilotCentralV402 = true;
  console.log('🚀 Crypto Copilot Central AI 4.0.2 loaded');

  const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
  let panel = null, currentTweet = null, currentFab = null, busy = false;

  const style=document.createElement('style');
  style.textContent=`
    .ccp402-fab{width:36px!important;height:36px!important;min-width:36px!important;margin:0 4px!important;padding:3px!important;border:1px solid rgba(120,215,255,.42)!important;border-radius:11px!important;background:#09101f!important;cursor:pointer!important;box-shadow:0 7px 22px rgba(90,105,255,.42)!important;display:grid!important;place-items:center!important;overflow:hidden!important}
    .ccp402-panel{position:fixed;z-index:2147483647;width:370px;max-width:calc(100vw - 20px);max-height:min(650px,calc(100vh - 20px));overflow:auto;background:#090d14;color:#f4f7fb;border:1px solid rgba(255,255,255,.12);border-radius:20px;box-shadow:0 30px 90px rgba(0,0,0,.7);font:13px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    .ccp402-head{padding:16px;background:linear-gradient(135deg,rgba(105,121,255,.2),rgba(154,105,255,.05));border-bottom:1px solid rgba(255,255,255,.08)}
    .ccp402-brand{display:flex;align-items:center;gap:10px}.ccp402-logo{width:36px;height:36px;border-radius:11px;display:grid;place-items:center;background:linear-gradient(135deg,#6478ff,#9b69ff);font-size:18px}.ccp402-title{font-weight:850;font-size:15px}.ccp402-sub{font-size:10px;color:#8993a5;margin-top:3px}
    .ccp402-status{margin:11px 12px 4px;padding:9px 11px;border-radius:11px;background:rgba(255,255,255,.035);color:#aeb7c5;font-size:10px}.ccp402-status.ok{color:#75e2a5;background:rgba(50,210,125,.08)}.ccp402-status.err{color:#ff8796;background:rgba(255,70,95,.08)}
    .ccp402-context{margin:10px 12px;padding:11px;border:1px solid rgba(255,255,255,.07);border-radius:13px;color:#aeb7c5;font-size:11px;line-height:1.5;max-height:120px;overflow:auto}
    .ccp402-body{padding:10px}.ccp402-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ccp402-btn,.ccp402-back{border:1px solid rgba(255,255,255,.08);border-radius:12px;background:rgba(255,255,255,.035);color:#edf0f5;cursor:pointer}.ccp402-btn{min-height:70px;padding:10px;text-align:left}.ccp402-btn:hover,.ccp402-back:hover{background:rgba(105,121,255,.1);border-color:rgba(105,121,255,.3)}.ccp402-icon{display:block;font-size:17px;margin-bottom:6px}.ccp402-btn strong{display:block;font-size:11px}.ccp402-btn span{display:block;color:#748095;font-size:9px;margin-top:3px}.ccp402-back{width:100%;margin-top:8px;padding:10px}.ccp402-loading{text-align:center;padding:28px;color:#aeb7c5}.ccp402-dot{display:inline-block;width:5px;height:5px;border-radius:50%;background:#7888ff;margin:12px 3px 0;animation:ccp402p 1s infinite alternate}.ccp402-dot:nth-child(2){animation-delay:.15s}.ccp402-dot:nth-child(3){animation-delay:.3s}@keyframes ccp402p{to{opacity:.2;transform:translateY(-3px)}}
    .ccp402-translation-head{padding:4px 3px 8px;color:#727d90;font-size:9px;font-weight:800;letter-spacing:.13em}.ccp402-translation{margin:4px 0 10px!important;padding:14px!important;border-radius:14px!important;background:rgba(105,121,255,.09)!important;border:1px solid rgba(105,121,255,.18)!important;color:#f2f4f8!important;direction:rtl!important;text-align:right!important;line-height:2!important;white-space:pre-wrap!important;max-height:360px!important;overflow:auto!important}
  `;
  document.documentElement.appendChild(style);

  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const norm=s=>String(s??'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
  const tweetText=t=>norm(t?.querySelector('[data-testid="tweetText"]')?.innerText||'');
  const replyBtn=t=>t?.querySelector('[data-testid="reply"]');
  const retweetBtn=t=>t?.querySelector('[data-testid="retweet"],[data-testid="unretweet"]');
  const visible=e=>{if(!e||!e.isConnected)return false;const r=e.getBoundingClientRect(),c=getComputedStyle(e);return r.width>0&&r.height>0&&c.display!=='none'&&c.visibility!=='hidden'};
  const editors=scope=>[...scope.querySelectorAll('[data-testid="tweetTextarea_0"][contenteditable="true"],[data-testid="tweetTextarea_0"] [contenteditable="true"],[role="textbox"][contenteditable="true"],[contenteditable="true"]')].filter(visible);
  const article=t=>t?.closest?.('article')||t;
  const editorText=e=>norm(e?.innerText||e?.textContent||'');

  function findReplyEditor(tweet){
    const a=article(tweet);const local=a?editors(a).filter(e=>!e.closest('.ccp402-panel')):[];if(local.length)return local[0];
    const dialogs=[...document.querySelectorAll('[role="dialog"],[data-testid="modalDialog"]')].filter(visible).reverse();
    for(const d of dialogs){const e=editors(d).find(x=>!x.closest('.ccp402-panel'));if(e)return e;}
    return editors(document).find(e=>!e.closest('.ccp402-panel')&&/reply/i.test(String(e.getAttribute('aria-label')||'')))||null;
  }
  async function ensureReplyEditor(tweet){
    let e=findReplyEditor(tweet);if(e)return e;const b=replyBtn(tweet);if(!b)return null;b.click();
    for(let i=0;i<70;i++){await sleep(150);e=findReplyEditor(tweet);if(e)return e;}return null;
  }
  function setEditorText(e,text){
    if(!e||!visible(e))return false;e.focus();try{document.execCommand('selectAll',false,null)}catch{}try{document.execCommand('insertText',false,text)}catch{}
    if(editorText(e)!==norm(text)){try{e.innerHTML='';const n=document.createTextNode(text);e.appendChild(n);e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}))}catch{}}
    e.dispatchEvent(new Event('change',{bubbles:true}));return editorText(e)===norm(text);
  }
  async function openNewPost(){const b=document.querySelector('[data-testid="SideNav_NewTweet_Button"]');if(!b)return null;const before=new Set(editors(document));b.click();for(let i=0;i<70;i++){await sleep(150);const e=editors(document).find(x=>!x.closest('.ccp402-panel')&&!before.has(x));if(e)return e}return null}
  async function openDialogEditor(){for(let i=0;i<70;i++){const d=[...document.querySelectorAll('[role="dialog"]')].filter(visible).reverse()[0];if(d){const e=editors(d)[0];if(e)return e}await sleep(150)}return null}
  function close(){panel?.remove();panel=null;currentTweet=null;currentFab=null;busy=false}
  function status(text,type=''){const s=panel?.querySelector('.ccp402-status');if(s){s.textContent=text;s.className='ccp402-status '+type}}
  function loading(text){const b=panel?.querySelector('.ccp402-body');if(b)b.innerHTML=`<div class="ccp402-loading">${esc(text)}<br><span class="ccp402-dot"></span><span class="ccp402-dot"></span><span class="ccp402-dot"></span></div>`}
  function button(icon,title,sub,fn){const b=document.createElement('button');b.type='button';b.className='ccp402-btn';b.innerHTML=`<span class="ccp402-icon">${icon}</span><strong>${esc(title)}</strong><span>${esc(sub)}</span>`;b.onclick=e=>{e.preventDefault();e.stopPropagation();fn()};return b}
  function askAI(messages,temperature=.8){return new Promise(resolve=>{let done=false;const timer=setTimeout(()=>{if(!done){done=true;resolve({ok:false,error:'AI request timed out'})}},30000);chrome.runtime.sendMessage({type:'CCP_AI',model:'openrouter/auto',temperature,messages},r=>{if(done)return;done=true;clearTimeout(timer);if(chrome.runtime.lastError)return resolve({ok:false,error:chrome.runtime.lastError.message});resolve(r?.ok?{ok:true,text:norm(r.text)}:{ok:false,error:r?.error||'Central AI request failed'})})})}
  const emoji=/[\p{Extended_Pictographic}]/gu;
  function oneEmoji(t){const s=norm(t),m=s.match(emoji)||[];if(m.length===1)return s;if(m.length>1){let first=true;return s.replace(emoji,()=>first?(first=false,m[0]):'').replace(/\s{2,}/g,' ').trim()}return `${s} 👀`}
  function cleanReply(t,src){const o=norm(t).replace(/^reply\s*:\s*/i,'').replace(/^['"“”]+|['"“”]+$/g,'');if(!o||norm(o).toLowerCase()===norm(src).toLowerCase())return '';return oneEmoji(o)}

  async function smartReply(){if(busy||!currentTweet)return;busy=true;try{const src=tweetText(currentTweet);if(!src)throw new Error('Tweet text not found');loading('Generating natural reply…');let r=await askAI([{role:'system',content:'Write one short natural human-sounding Crypto Twitter reply. Do not echo, restate or summarize the source. Under 25 words. No hashtags. Exactly one fitting emoji. Output only the reply.'},{role:'user',content:src}],.82);let reply=r.ok?cleanReply(r.text,src):'';if(!reply){r=await askAI([{role:'system',content:'Write a completely different short natural reaction. Do not reuse wording from the source post. Under 25 words. No hashtags. Exactly one fitting emoji. Output only the reply.'},{role:'user',content:src}],.95);reply=r.ok?cleanReply(r.text,src):''}if(!reply)throw new Error(r.error||'Generated reply was empty');loading('Opening this Tweet reply box…');const e=await ensureReplyEditor(currentTweet);if(!e)throw new Error('Reply composer for this Tweet was not found');if(!setEditorText(e,reply))throw new Error('X did not accept the generated reply');close()}catch(e){status(`❌ ${e.message||'Smart Reply failed'}`,'err');busy=false}}
  async function translate(){if(busy||!currentTweet)return;busy=true;try{const src=tweetText(currentTweet);if(!src)throw new Error('Tweet text not found');loading('Translating to Persian…');const r=await askAI([{role:'system',content:'Translate this X post into natural fluent Persian. Preserve usernames, names, tickers, links and numbers. Output only the translation.'},{role:'user',content:src}],.25);if(!r.ok)throw new Error(r.error);const body=panel.querySelector('.ccp402-body');body.innerHTML=`<div class="ccp402-translation-head">PERSIAN TRANSLATION</div><div class="ccp402-translation">${esc(r.text)}</div><button type="button" class="ccp402-back" id="ccp-done">✓ Done</button>`;panel.querySelector('#ccp-done').onclick=close;status('✓ Translation ready','ok')}catch(e){status(`❌ ${e.message||'Translation failed'}`,'err')}finally{busy=false}}
  async function rewrite(){if(busy||!currentTweet)return;busy=true;try{status('Rewriting…');const r=await askAI([{role:'system',content:'Rewrite this crypto/social post to sound sharper, clearer and genuinely human. Preserve meaning. Output only the rewritten post.'},{role:'user',content:tweetText(currentTweet)}],.78);if(!r.ok)throw new Error(r.error);close();const e=await openNewPost();if(!e)throw new Error('New post composer not found');if(!setEditorText(e,r.text))throw new Error('Could not insert rewritten post')}catch(e){status(`❌ ${e.message||'Rewrite failed'}`,'err');busy=false}}
  async function thread(){if(busy||!currentTweet)return;busy=true;try{status('Building thread…');const r=await askAI([{role:'system',content:'Create exactly 3 connected Crypto Twitter posts. Number them 1/3, 2/3, 3/3. Concise, natural and non-repetitive. Output only the three posts separated by blank lines.'},{role:'user',content:tweetText(currentTweet)}],.8);if(!r.ok)throw new Error(r.error);close();const e=await openNewPost();if(!e)throw new Error('New post composer not found');if(!setEditorText(e,r.text))throw new Error('Could not insert thread')}catch(e){status(`❌ ${e.message||'Thread failed'}`,'err');busy=false}}
  async function quote(){if(busy||!currentTweet)return;busy=true;try{status('Writing quote comment…');const r=await askAI([{role:'system',content:'Write one fresh quote-tweet comment reacting to the idea. Do not restate or paraphrase the source. Under 25 words. No hashtags. Exactly one fitting emoji. Output only the comment.'},{role:'user',content:tweetText(currentTweet)}],.85);if(!r.ok)throw new Error(r.error);const rb=retweetBtn(currentTweet);if(!rb)throw new Error('Quote button not found');rb.click();for(let i=0;i<40;i++){await sleep(120);const item=[...document.querySelectorAll('[role="menuitem"],[role="option"]')].find(x=>/quote/i.test(norm(x.innerText||x.getAttribute('aria-label')||'')));if(item){item.click();const e=await openDialogEditor();if(!e||!setEditorText(e,oneEmoji(r.text)))throw new Error('Could not insert quote');close();return}}throw new Error('Quote option not found')}catch(e){status(`❌ ${e.message||'Quote failed'}`,'err');busy=false}}

  function openPanel(tweet,fab){close();currentTweet=tweet;currentFab=fab;panel=document.createElement('div');panel.className='ccp402-panel';panel.innerHTML=`<div class="ccp402-head"><div class="ccp402-brand"><div class="ccp402-logo">✦</div><div><div class="ccp402-title">Crypto Copilot</div><div class="ccp402-sub">Central AI • Cloudflare</div></div></div></div><div class="ccp402-status ok">✓ Central AI ready</div><div class="ccp402-context">${esc(tweetText(tweet).slice(0,900)||'Tweet text unavailable')}</div><div class="ccp402-body"><div class="ccp402-grid" id="ccp-grid"></div></div>`;document.body.appendChild(panel);const r=fab.getBoundingClientRect(),w=370,h=Math.min(650,innerHeight-20);panel.style.left=`${Math.max(10,Math.min(r.right-w,innerWidth-w-10))}px`;panel.style.top=`${Math.max(10,Math.min(r.bottom+8,innerHeight-h-10))}px`;const g=panel.querySelector('#ccp-grid');g.append(button('⚡','Smart Reply','Generate & insert automatically',smartReply),button('🔁','Smart Quote','Fresh quote comment',quote),button('🌍','Translate','Natural Persian',translate),button('✎','Rewrite','Sharper new post',rewrite),button('🧵','Thread','Three connected posts',thread))}
  function attach(tweet){if(!tweet||tweet.querySelector('.ccp402-fab'))return;const host=tweet.querySelector('[role="group"]')||replyBtn(tweet)?.parentElement;if(!host)return;const b=document.createElement('button');b.type='button';b.className='ccp402-fab';b.title='Crypto Copilot';b.setAttribute('aria-label','Crypto Copilot');b.innerHTML='<span style="font-size:16px;color:#fff">✦</span>';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openPanel(tweet,b)},{capture:true});host.appendChild(b)}
  function scan(){document.querySelectorAll('article').forEach(attach)}
  scan();new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel)close()});document.addEventListener('click',e=>{if(panel&&!panel.contains(e.target)&&!e.target.closest('.ccp402-fab'))close()},true);
  console.log('🚀 Crypto Copilot Central AI 4.0.2 loaded');
})();
