(() => {
  if (window.__cryptoCopilotV223) return;
  window.__cryptoCopilotV223 = true;

  const sleep = ms => new Promise(r => setTimeout(r, ms));
  let panel = null, currentTweet = null, currentFab = null, busy = false;

  const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const normalizeText = s => String(s||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
  const tweetText = t => t?.querySelector('[data-testid="tweetText"]')?.innerText?.trim() || '';
  const replyButton = t => t?.querySelector('[data-testid="reply"]');
  const retweetButton = t => t?.querySelector('[data-testid="retweet"],[data-testid="unretweet"]');
  const isVisible = el => { if(!el||!el.isConnected)return false; const r=el.getBoundingClientRect(),c=getComputedStyle(el); return r.width>0&&r.height>0&&c.display!=='none'&&c.visibility!=='hidden'; };
  const editorCandidates = scope => [...scope.querySelectorAll('[data-testid="tweetTextarea_0"][contenteditable="true"],[data-testid="tweetTextarea_0"] [contenteditable="true"],[role="textbox"][contenteditable="true"],[contenteditable="true"]')].filter(isVisible);
  const editorText = e => normalizeText(e?.innerText||e?.textContent||'');

  const style=document.createElement('style');
  style.textContent=`
    .ccp223-fab{width:36px!important;height:36px!important;min-width:36px!important;margin:0 4px!important;padding:3px!important;border:1px solid rgba(120,215,255,.42)!important;border-radius:11px!important;background:#09101f!important;color:transparent!important;cursor:pointer!important;box-shadow:0 7px 22px rgba(90,105,255,.42)!important;display:grid!important;place-items:center!important;overflow:hidden!important;transition:transform .15s ease,filter .15s ease!important}.ccp223-fab:hover{transform:scale(1.06)!important;filter:brightness(1.08)!important}
    .ccp223-panel{position:fixed;z-index:2147483647;width:370px;max-width:calc(100vw - 20px);max-height:min(650px,calc(100vh - 20px));overflow:auto;background:#090d14;color:#f4f7fb;border:1px solid rgba(255,255,255,.12);border-radius:20px;box-shadow:0 30px 90px rgba(0,0,0,.7);font:13px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overscroll-behavior:contain}.ccp223-head{padding:16px;background:linear-gradient(135deg,rgba(105,121,255,.2),rgba(154,105,255,.05));border-bottom:1px solid rgba(255,255,255,.08)}.ccp223-brand{display:flex;align-items:center;gap:10px}.ccp223-logo{width:36px;height:36px;border-radius:11px;display:grid;place-items:center;background:linear-gradient(135deg,#6478ff,#9b69ff);font-size:17px}.ccp223-title{font-weight:850;font-size:15px}.ccp223-sub{font-size:10px;color:#8993a5;margin-top:3px}.ccp223-status{margin:11px 12px 4px;padding:9px 11px;border-radius:11px;background:rgba(255,255,255,.035);color:#aeb7c5;font-size:10px}.ccp223-status.ok{color:#75e2a5;background:rgba(50,210,125,.08)}.ccp223-status.err{color:#ff8796;background:rgba(255,70,95,.08)}.ccp223-context{margin:10px 12px;padding:11px;border:1px solid rgba(255,255,255,.07);border-radius:13px;color:#aeb7c5;font-size:11px;line-height:1.5;max-height:92px;overflow:auto}.ccp223-body{padding:10px}.ccp223-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ccp223-btn,.ccp223-back{border:1px solid rgba(255,255,255,.08);border-radius:12px;background:rgba(255,255,255,.035);color:#edf0f5;cursor:pointer}.ccp223-btn{min-height:70px;padding:10px;text-align:left}.ccp223-btn:hover,.ccp223-back:hover{background:rgba(105,121,255,.1);border-color:rgba(105,121,255,.3)}.ccp223-icon{display:block;font-size:17px;margin-bottom:6px}.ccp223-btn strong{display:block;font-size:11px}.ccp223-btn span{display:block;color:#748095;font-size:9px;margin-top:3px}.ccp223-generate{width:100%;margin-top:9px;padding:12px;border:0;border-radius:12px;background:linear-gradient(135deg,#6579ff,#9a69ff);color:#fff;font-weight:850;cursor:pointer}.ccp223-loading{text-align:center;padding:28px;color:#aeb7c5}.ccp223-dot{display:inline-block;width:5px;height:5px;border-radius:50%;background:#7888ff;margin:12px 3px 0}.ccp223-translation-head{padding:4px 3px 8px;color:#727d90;font-size:9px;font-weight:800;letter-spacing:.13em}.ccp223-translation{margin:4px 0 10px!important;padding:14px!important;border-radius:14px!important;background:rgba(105,121,255,.09)!important;border:1px solid rgba(105,121,255,.18)!important;color:#f2f4f8!important;direction:rtl!important;text-align:right!important;line-height:2!important;white-space:pre-wrap!important;max-height:360px!important;overflow:auto!important}`;
  document.documentElement.appendChild(style);

  function tweetArticle(node){return node?.closest?.('article')||node||null;}
  function editorScore(editor,tweet){if(!isVisible(editor))return -1e9;const article=tweetArticle(tweet);if(!article)return -1e9;let score=0;if(article.contains(editor))score+=12000;const label=String(editor.getAttribute('aria-label')||editor.getAttribute('data-testid')||'').toLowerCase();if(/reply|post your reply/.test(label))score+=6000;if(/new post|compose/.test(label))score-=8000;const er=editor.getBoundingClientRect(),ar=article.getBoundingClientRect();score-=Math.min(6000,Math.hypot((er.left+er.width/2)-(ar.left+ar.width/2),(er.top+er.height/2)-(ar.top+ar.height/2)));return score;}
  function findReplyEditor(tweet,before=new Set()){const article=tweetArticle(tweet);if(!article)return null;const local=editorCandidates(article);if(local.length)return local.sort((a,b)=>editorScore(b,tweet)-editorScore(a,tweet))[0];const fresh=editorCandidates(document).filter(e=>!before.has(e)&&!e.closest('.ccp223-panel')).sort((a,b)=>editorScore(b,tweet)-editorScore(a,tweet));return fresh[0]&&editorScore(fresh[0],tweet)>1500?fresh[0]:null;}
  async function waitForReplyEditor(tweet,before){const end=Date.now()+10000;while(Date.now()<end){const e=findReplyEditor(tweet,before);if(e)return e;await sleep(120);}return null;}
  async function openReplyComposer(tweet){const before=new Set(editorCandidates(document));const button=replyButton(tweet);if(!button)return null;button.click();return waitForReplyEditor(tweet,before);}
  async function openDialogEditor(timeout=10000){const end=Date.now()+timeout;while(Date.now()<end){const d=document.querySelector('[role="dialog"]');const e=d?editorCandidates(d)[0]:null;if(e)return e;await sleep(120);}return null;}
  async function openNewPost(){const before=new Set(editorCandidates(document));const btn=document.querySelector('[data-testid="SideNav_NewTweet_Button"]');if(!btn)return null;btn.click();const end=Date.now()+10000;while(Date.now()<end){const d=document.querySelector('[role="dialog"]');if(d){const e=editorCandidates(d).find(x=>!before.has(x));if(e)return e;}await sleep(120);}return null;}
  function comparable(s){return normalizeText(s).normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}\s]+/gu,' ').replace(/\s+/g,' ').trim();}
  function similarity(a,b){const x=comparable(a).split(' ').filter(w=>w.length>2),y=comparable(b).split(' ').filter(w=>w.length>2);if(!x.length||!y.length)return 0;const set=new Set(x);let n=0;for(const w of y)if(set.has(w))n++;return n/y.length;}
  function repeated(s){const p=comparable(s).split(/[.!?]+/).map(x=>x.trim()).filter(Boolean);for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++)if(p[i].length>16&&p[i]===p[j])return true;return false;}
  const emojiRe=/[\p{Extended_Pictographic}]/gu;
  function ensureOneEmoji(text,source=''){const s=String(text||'').trim(),found=s.match(emojiRe)||[];if(found.length===1)return s;if(found.length>1){let first=true;return s.replace(emojiRe,()=>first?(first=false,found[0]):'').replace(/\s{2,}/g,' ').trim();}const low=String(source).toLowerCase();const e=/rocket|launch|base|token|airdrop|profit|bull|market|trade|price|pump|up|growth/.test(low)?'🚀':/smart|learn|idea|think|analysis|why/.test(low)?'🧠':'👀';return `${s} ${e}`.trim();}
  function cleanReply(text,source){let o=normalizeText(text).replace(/^reply\s*:\s*/i,'').replace(/^['"“”]+|['"“”]+$/g,'').trim();if(!o||comparable(o)===comparable(source)||similarity(source,o)>.68||repeated(o))return '';return ensureOneEmoji(o,source);}
  function selectAllEditorContent(editor){editor.focus();const sel=window.getSelection(),range=document.createRange();range.selectNodeContents(editor);sel.removeAllRanges();sel.addRange(range);}
  function fireInput(editor,text){try{editor.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}));}catch{editor.dispatchEvent(new Event('input',{bubbles:true}));}}
  async function insertIntoComposer(editor,text){if(!editor||!isVisible(editor))return{ok:false,error:'Editor is not visible'};if(editorText(editor))return{ok:false,error:'Composer already contains text'};const expected=normalizeText(text);selectAllEditorContent(editor);try{document.execCommand('insertText',false,text);}catch{}fireInput(editor,text);await sleep(350);let actual=editorText(editor);if(actual===expected)return{ok:true,actualText:actual};try{selectAllEditorContent(editor);const sel=window.getSelection(),range=sel.getRangeAt(0);range.deleteContents();const node=document.createTextNode(text);range.insertNode(node);range.setStartAfter(node);range.collapse(true);sel.removeAllRanges();sel.addRange(range);fireInput(editor,text);}catch(e){return{ok:false,error:e?.message||'Composer insertion failed'}}await sleep(450);actual=editorText(editor);return actual===expected?{ok:true,actualText:actual}:{ok:false,error:`X did not accept the generated text (${actual||'empty'})`};}
  function close(){panel?.remove();panel=null;currentTweet=null;currentFab=null;busy=false;}
  function position(){if(!panel||!currentFab)return;const r=currentFab.getBoundingClientRect(),w=Math.min(370,innerWidth-20),h=panel.offsetHeight||420;let top=r.bottom+8;if(top+h>innerHeight-10)top=r.top-h-8;panel.style.left=Math.max(10,Math.min(r.left,innerWidth-w-10))+'px';panel.style.top=Math.max(10,Math.min(top,innerHeight-h-10))+'px';}
  function setStatus(msg,type=''){const e=panel?.querySelector('.ccp223-status');if(e){e.textContent=msg;e.className='ccp223-status '+type;position();}}
  function loading(msg){const b=panel?.querySelector('.ccp223-body');if(b){b.innerHTML=`<div class="ccp223-loading">${esc(msg)}<br><span class="ccp223-dot"></span><span class="ccp223-dot"></span><span class="ccp223-dot"></span></div>`;position();}}
  function action(icon,title,desc,fn){const b=document.createElement('button');b.type='button';b.className='ccp223-btn';b.innerHTML=`<span class="ccp223-icon">${icon}</span><strong>${esc(title)}</strong><span>${esc(desc)}</span>`;b.onclick=e=>{e.preventDefault();e.stopPropagation();fn();};return b;}
  function askAI(messages,temperature=.82){return new Promise(resolve=>{let done=false;const timer=setTimeout(()=>{if(!done){done=true;resolve({ok:false,error:'AI request timed out'})}},30000);chrome.runtime.sendMessage({type:'CCP_AI',temperature,messages},r=>{if(done)return;done=true;clearTimeout(timer);if(chrome.runtime.lastError)return resolve({ok:false,error:chrome.runtime.lastError.message});resolve(r?.ok?{ok:true,text:String(r.text||'').trim()}:{ok:false,error:r?.error||'AI request failed'});});});}
  const replySystem='Write one short natural human Crypto Twitter reply. Never echo, paraphrase or summarize the source Tweet. Exactly ONE fitting emoji. No hashtags. No quotes. Output only the reply.';
  async function smartReply(tweet){if(busy)return;busy=true;const source=tweetText(tweet);if(!source){setStatus('❌ Tweet text not found','err');busy=false;return;}loading('Generating natural reply…');let r=await askAI([{role:'system',content:replySystem},{role:'user',content:`Create ONE fresh reaction to this Tweet. Under 25 words. Exactly one natural emoji.\n\nSOURCE:\n${source}`}]);let reply=r.ok?cleanReply(r.text,source):'';if(!reply){r=await askAI([{role:'system',content:replySystem},{role:'user',content:`Create a completely different reaction with different vocabulary and sentence structure. Do not reuse wording from the Tweet. Under 25 words. Exactly one natural emoji.\n\nSOURCE:\n${source}`}],.95);reply=r.ok?cleanReply(r.text,source):'';}if(!reply){setStatus(`❌ ${r.error||'Generated reply rejected'}`,'err');busy=false;return;}loading('Opening this Tweet reply box…');const editor=await openReplyComposer(tweet);if(!editor){setStatus('❌ Reply composer for this Tweet was not found','err');busy=false;return;}const result=await insertIntoComposer(editor,reply);if(!result.ok){setStatus(`❌ ${result.error}`,'err');busy=false;return;}setStatus('✓ Reply inserted and verified','ok');await sleep(600);close();}
  async function translate(tweet){if(busy)return;busy=true;const source=tweetText(tweet);if(!source){setStatus('❌ Tweet text not found','err');busy=false;return;}loading('Translating…');const r=await askAI([{role:'system',content:'Translate this Crypto Twitter text into natural fluent Persian. Preserve names, tickers and crypto terminology. Output only the translation.'},{role:'user',content:source}],.25);if(!r.ok){setStatus(`❌ ${r.error}`,'err');busy=false;return;}const body=panel?.querySelector('.ccp223-body');if(body){body.innerHTML='<div class="ccp223-translation-head">PERSIAN TRANSLATION</div><div class="ccp223-translation">'+esc(r.text)+'</div><button type="button" class="ccp223-back" id="translation-done">✓ Done</button>';body.querySelector('#translation-done').onclick=()=>close();position();}setStatus('✓ Translation ready','ok');busy=false;}
  async function rewrite(tweet){if(busy)return;busy=true;loading('Rewriting…');const r=await askAI([{role:'system',content:'Rewrite this crypto post to sound sharper, clearer and genuinely human. Preserve meaning. Exactly one tasteful emoji. Output only the rewritten post.'},{role:'user',content:tweetText(tweet)}],.78);if(!r.ok){setStatus(`❌ ${r.error}`,'err');busy=false;return;}close();const e=await openNewPost();if(!e){busy=false;return;}const out=await insertIntoComposer(e,r.text);if(!out.ok)console.warn('Crypto Copilot rewrite:',out.error);busy=false;}
  async function thread(tweet){if(busy)return;busy=true;loading('Building 3-post thread…');const r=await askAI([{role:'system',content:'Create exactly 3 connected Crypto Twitter posts. Number them 1/3, 2/3, 3/3. Human, concise and non-repetitive. One fitting emoji per post. Output only the three posts separated by blank lines.'},{role:'user',content:tweetText(tweet)}],.8);if(!r.ok){setStatus(`❌ ${r.error}`,'err');busy=false;return;}close();const e=await openNewPost();if(!e){busy=false;return;}const out=await insertIntoComposer(e,r.text);if(!out.ok)console.warn('Crypto Copilot thread:',out.error);busy=false;}
  async function quote(tweet){if(busy)return;busy=true;loading('Writing quote comment…');const r=await askAI([{role:'system',content:'Write one fresh quote-tweet comment reacting to the idea. Do not restate or paraphrase the source. Under 25 words. Exactly one fitting emoji. No hashtags. Output only the comment.'},{role:'user',content:tweetText(tweet)}],.85);if(!r.ok){setStatus(`❌ ${r.error}`,'err');busy=false;return;}const rb=retweetButton(tweet);if(!rb){setStatus('❌ Quote button not found','err');busy=false;return;}rb.click();const end=Date.now()+5000;let item=null;while(Date.now()<end&&!item){item=[...document.querySelectorAll('[role="menuitem"],[role="option"]')].find(x=>/quote/i.test((x.innerText||x.getAttribute('aria-label')||'').trim()));if(!item)await sleep(120);}if(!item){setStatus('❌ Quote option not found','err');busy=false;return;}item.click();const e=await openDialogEditor(10000);if(!e){setStatus('❌ Quote composer not found','err');busy=false;return;}const out=await insertIntoComposer(e,ensureOneEmoji(r.text,tweetText(tweet)));if(!out.ok){setStatus(`❌ ${out.error}`,'err');busy=false;return;}setStatus('✓ Quote inserted','ok');await sleep(500);close();}
  function visibleTrends(){const out=[],seen=new Set();for(const a of [...document.querySelectorAll('a[href*="/search?q="]')]){const t=normalizeText(a.innerText||a.textContent);if(!t||t.length<2||t.length>120||/show more|search|what's happening/i.test(t)||seen.has(t))continue;seen.add(t);out.push(t);if(out.length>=8)break;}return out;}
  async function trendRadar(){const trends=visibleTrends();if(!trends.length){setStatus('⚠️ Open X Explore → Trending first','err');return;}const body=panel.querySelector('.ccp223-body');body.innerHTML='<div style="padding:4px;color:#727d90;font-size:9px;font-weight:800;letter-spacing:.13em">VISIBLE X TRENDS</div>'+trends.map((t,i)=>`<button type="button" class="ccp223-back" data-t="${i}" style="margin-top:7px">📈 ${esc(t)}</button>`).join('');body.querySelectorAll('[data-t]').forEach(b=>b.onclick=async()=>{if(busy)return;busy=true;loading('Writing trend post…');const r=await askAI([{role:'system',content:'Write one natural Crypto Twitter post about the visible trend. Do not invent facts. Exactly one fitting emoji. Output only the post.'},{role:'user',content:`Visible trend: ${trends[Number(b.dataset.t)]}`}],.82);if(!r.ok){setStatus(`❌ ${r.error}`,'err');busy=false;return;}close();const e=await openNewPost();if(e){const out=await insertIntoComposer(e,r.text);if(!out.ok)console.warn('Crypto Copilot trend:',out.error);}busy=false;});position();}
  function replyUI(tweet){smartReply(tweet);}
  function openPanel(tweet,fab){close();currentTweet=tweet;currentFab=fab;panel=document.createElement('div');panel.className='ccp223-panel';const preview=tweetText(tweet);panel.innerHTML=`<div class="ccp223-head"><div class="ccp223-brand"><div class="ccp223-logo">✦</div><div><div class="ccp223-title">Crypto Copilot</div><div class="ccp223-sub">Natural AI tools for X</div></div></div></div>${preview?`<div class="ccp223-context">${esc(preview.slice(0,180))}${preview.length>180?'…':''}</div>`:''}<div class="ccp223-status">Connecting to Central AI…</div><div class="ccp223-body"><div style="padding:4px 3px 8px;color:#727d90;font-size:9px;font-weight:800;letter-spacing:.13em">AI TOOLS</div><div class="ccp223-grid" id="grid"></div></div>`;document.body.appendChild(panel);const g=panel.querySelector('#grid');g.appendChild(action('⚡','Smart Reply','Generate & insert automatically',()=>replyUI(tweet)));g.appendChild(action('🔁','Smart Quote','Fresh quote comment',()=>quote(tweet)));g.appendChild(action('🌍','Translate','Natural Persian',()=>translate(tweet)));g.appendChild(action('✎','Rewrite','Sharper new post',()=>rewrite(tweet)));g.appendChild(action('🧵','Thread','Three connected posts',()=>thread(tweet)));g.appendChild(action('📈','Trend Radar','Use visible X trends',()=>trendRadar()));setStatus('✓ Central AI ready','ok');position();}
  function attach(tweet){if(tweet.querySelector('.ccp223-fab'))return;const host=tweet.querySelector('[role="group"]')||tweet.querySelector('[data-testid="reply"]')?.parentElement;if(!host)return;const b=document.createElement('button');b.className='ccp223-fab';b.type='button';b.textContent='✦';b.title='Crypto Copilot';b.setAttribute('aria-label','Crypto Copilot');b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openPanel(tweet,b)},{capture:true});host.appendChild(b);}
  function scan(){document.querySelectorAll('article').forEach(attach);}
  scan();new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});window.addEventListener('scroll',position,true);window.addEventListener('resize',position);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel)close();});document.addEventListener('click',e=>{if(panel&&!panel.contains(e.target)&&!e.target.closest('.ccp223-fab'))close();});
  console.log('🚀 Crypto Copilot V2.2.3 loaded');
})();